name: Release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn

      - name: Build react-native-swipeable-card-stack
        run: yarn build

      - name: Test formatting
        run: yarn test:format

      - name: Test linting
        run: yarn test:lint

      - name: Run unit tests
        run: yarn test:jest

      - name: Publish to npm
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
